import 'package:book_app/features/category/model/category_model.dart'
    show BookCategory;

final List<BookCategory> bookCategories = [
  BookCategory(
    id: 'c1',
    title: 'Self Help',
    icon: '💡',
    bookCount: 12,
    route: '',
  ),
  BookCategory(
    id: 'c2',
    title: 'Fiction',
    icon: '📖',
    bookCount: 20,
    route: '',
  ),
  BookCategory(
    id: 'c3',
    title: 'Non-Fiction',
    icon: '📚',
    bookCount: 15,
    route: '',
  ),
  BookCategory(
    id: 'c4',
    title: 'Finance',
    icon: '💰',
    bookCount: 8,
    route: '',
  ),
  BookCategory(
    id: 'c5',
    title: 'Business',
    icon: '📈',
    bookCount: 10,
    route: '',
  ),
  BookCategory(
    id: 'c6',
    title: 'Biography',
    icon: '👤',
    bookCount: 6,
    route: '',
  ),
  BookCategory(
    id: 'c7',
    title: 'Autobiography',
    icon: '📝',
    bookCount: 5,
    route: '',
  ),
  BookCategory(
    id: 'c8',
    title: 'Science',
    icon: '🔬',
    bookCount: 9,
    route: '',
  ),
  BookCategory(
    id: 'c9',
    title: 'Technology',
    icon: '💻',
    bookCount: 11,
    route: '',
  ),
  BookCategory(
    id: 'c10',
    title: 'Programming',
    icon: '👨‍💻',
    bookCount: 14,
    route: '',
  ),
  BookCategory(
    id: 'c11',
    title: 'History',
    icon: '🏛️',
    bookCount: 7,
    route: '',
  ),
  BookCategory(
    id: 'c12',
    title: 'Philosophy',
    icon: '🧠',
    bookCount: 4,
    route: '',
  ),
  BookCategory(
    id: 'c13',
    title: 'Psychology',
    icon: '🧘',
    bookCount: 6,
    route: '',
  ),
  BookCategory(
    id: 'c14',
    title: 'Romance',
    icon: '❤️',
    bookCount: 18,
    route: '',
  ),
  BookCategory(
    id: 'c15',
    title: 'Thriller',
    icon: '🔥',
    bookCount: 13,
    route: '',
  ),
  BookCategory(
    id: 'c16',
    title: 'Mystery',
    icon: '🕵️',
    bookCount: 9,
    route: '',
  ),
  BookCategory(
    id: 'c17',
    title: 'Fantasy',
    icon: '🧙',
    bookCount: 16,
    route: '',
  ),
  BookCategory(
    id: 'c18',
    title: 'Horror',
    icon: '👻',
    bookCount: 5,
    route: '',
  ),
  BookCategory(
    id: 'c19',
    title: 'Spirituality',
    icon: '🕉️',
    bookCount: 7,
    route: '',
  ),
  BookCategory(
    id: 'c20',
    title: 'Health & Fitness',
    icon: '🏋️',
    bookCount: 10,
    route: '',
  ),
  BookCategory(
    id: 'c21',
    title: 'Travel',
    icon: '✈️',
    bookCount: 6,
    route: '',
  ),
  BookCategory(
    id: 'c22',
    title: 'Education',
    icon: '🎓',
    bookCount: 8,
    route: '',
  ),
  BookCategory(
    id: 'c23',
    title: 'Children',
    icon: '🧸',
    bookCount: 12,
    route: '',
  ),
  BookCategory(
    id: 'c24',
    title: 'Poetry',
    icon: '📜',
    bookCount: 4,
    route: '',
  ),
  BookCategory(
    id: 'c25',
    title: 'Comics',
    icon: '🦸',
    bookCount: 9,
    route: '',
  ),
];